import { 
  GET_INGREDIENTS_REQUEST, GET_INGREDIENTS_SUCCESS, GET_INGREDIENTS_FAILED,
  GET_INGREDIENTS_CART, ADD_INGREDIENTS_CART, REMOVE_INGREDIENTS_CART, REMOVE_BUN_INGREDIENTS_CART, UPDATE_INGREDIENTS_CART, REMOVE_INGREDIENTS_ALL_CART,
  INGREDIENTS_MODAL_OPEN, INGREDIENTS_MODAL_CLOSE,
  getIngredients, addToCart,
} from './ingredients'

import { 
  POST_ORDER_REQUEST, GET_ORDER_SUCCESS, GET_ORDER_FAILED,
  postOrder
} from './order'

import {
  GET_USER_REQUEST, GET_USER_SUCCESS, GET_USER_FAILED,
  PATCH_USER_REQUEST, PATCH_USER_SUCCESS, PATCH_USER_FAILED,
  POST_FORGOT_REQUEST, POST_FORGOT_SUCCESS, POST_FORGOT_FAILED,
  POST_RESET_REQUEST, POST_RESET_SUCCESS, POST_RESET_FAILED,
  POST_LOGIN_REQUEST, POST_LOGIN_SUCCESS, POST_LOGIN_FAILED,
  POST_LOGOUT_REQUEST, POST_LOGOUT_SUCCESS, POST_LOGOUT_FAILED,
  POST_REGISTER_REQUEST, POST_REGISTER_SUCCESS, POST_REGISTER_FAILED,
  POST_TOKEN_REQUEST, POST_TOKEN_SUCCESS, POST_TOKEN_FAILED,
  register, login, logout, forgot, reset, getUser, updateUser, checkUserToken,
} from './user';

export const SET_TAB_ACTIVE = 'SET_TAB_ACTIVE';

export { 
  GET_INGREDIENTS_REQUEST, GET_INGREDIENTS_SUCCESS, GET_INGREDIENTS_FAILED,
  GET_INGREDIENTS_CART, ADD_INGREDIENTS_CART, REMOVE_INGREDIENTS_CART, REMOVE_BUN_INGREDIENTS_CART, UPDATE_INGREDIENTS_CART, REMOVE_INGREDIENTS_ALL_CART,
  INGREDIENTS_MODAL_OPEN, INGREDIENTS_MODAL_CLOSE,
  POST_ORDER_REQUEST, GET_ORDER_SUCCESS, GET_ORDER_FAILED,
  GET_USER_REQUEST, GET_USER_SUCCESS, GET_USER_FAILED,
  PATCH_USER_REQUEST, PATCH_USER_SUCCESS, PATCH_USER_FAILED,
  POST_FORGOT_REQUEST, POST_FORGOT_SUCCESS, POST_FORGOT_FAILED,
  POST_RESET_REQUEST, POST_RESET_SUCCESS, POST_RESET_FAILED,
  POST_LOGIN_REQUEST, POST_LOGIN_SUCCESS, POST_LOGIN_FAILED,
  POST_LOGOUT_REQUEST, POST_LOGOUT_SUCCESS, POST_LOGOUT_FAILED,
  POST_REGISTER_REQUEST, POST_REGISTER_SUCCESS, POST_REGISTER_FAILED,
  POST_TOKEN_REQUEST, POST_TOKEN_SUCCESS, POST_TOKEN_FAILED,

  register, login, logout, forgot, reset, getUser, updateUser, checkUserToken,
  postOrder,
  getIngredients, addToCart,
 };